shellEmulator: true

# eslint-disable-next-line pnpm/yaml-enforce-settings
trustPolicy: accept

packages:
  - docs
  - packages/*

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - simple-git-hooks
  - unrs-resolver
