/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DocsProjectCard: typeof import('./../../node_modules/.pnpm/@yunyoujun+docs@0.1.14_vite@8.0.2_@types+node@25.5.0_esbuild@0.27.3_jiti@2.6.1_sass@1.9_5106adb2c90dd6d9af0814c7748a90ab/node_modules/@yunyoujun/docs/client/components/DocsProjectCard.vue')['default']
    DocsProjectList: typeof import('./../../node_modules/.pnpm/@yunyoujun+docs@0.1.14_vite@8.0.2_@types+node@25.5.0_esbuild@0.27.3_jiti@2.6.1_sass@1.9_5106adb2c90dd6d9af0814c7748a90ab/node_modules/@yunyoujun/docs/client/components/DocsProjectList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const DocsProjectCard: typeof import('./../../node_modules/.pnpm/@yunyoujun+docs@0.1.14_vite@8.0.2_@types+node@25.5.0_esbuild@0.27.3_jiti@2.6.1_sass@1.9_5106adb2c90dd6d9af0814c7748a90ab/node_modules/@yunyoujun/docs/client/components/DocsProjectCard.vue')['default']
  const DocsProjectList: typeof import('./../../node_modules/.pnpm/@yunyoujun+docs@0.1.14_vite@8.0.2_@types+node@25.5.0_esbuild@0.27.3_jiti@2.6.1_sass@1.9_5106adb2c90dd6d9af0814c7748a90ab/node_modules/@yunyoujun/docs/client/components/DocsProjectList.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
}