// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AboutMe: typeof import('./components/AboutMe.vue')['default']
    BaseFooter: typeof import('./components/BaseFooter.vue')['default']
    ChooseFood: typeof import('./components/ChooseFood.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    DishTag: typeof import('./components/tags/DishTag.vue')['default']
    InstallPwa: typeof import('./components/InstallPwa.vue')['default']
    MeatTag: typeof import('./components/tags/MeatTag.vue')['default']
    Menu: typeof import('./components/Menu.vue')['default']
    README: typeof import('./components/README.md')['default']
    ReloadPrompt: typeof import('./components/ReloadPrompt.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchFoodInput: typeof import('./components/SearchFoodInput.vue')['default']
    StapleTag: typeof import('./components/tags/StapleTag.vue')['default']
    Switch: typeof import('./components/Switch.vue')['default']
    ToggleMode: typeof import('./components/ToggleMode.vue')['default']
    ToolTag: typeof import('./components/tags/ToolTag.vue')['default']
    VegetableTag: typeof import('./components/tags/VegetableTag.vue')['default']
    WrapperMd: typeof import('./components/WrapperMd.vue')['default']
  }
}
